// ============================================================================
// SPW_CMS_PAGE_HISTORY — 페이지 이력 테이블 SQL 맵퍼
// ============================================================================

/** 다음 버전 번호 조회 */
export const PAGE_HISTORY_NEXT_VERSION = `
  SELECT NVL(MAX(VERSION), 0) + 1 AS NEXT_VERSION
  FROM SPW_CMS_PAGE_HISTORY
  WHERE PAGE_ID = :pageId
`;

/** 이력 생성 — 현재 PAGE 스냅샷 복사 (트랜잭션 내 사용) */
export const PAGE_HISTORY_INSERT = `
  INSERT INTO SPW_CMS_PAGE_HISTORY (
    PAGE_ID, VERSION,
    PAGE_NAME, OWNER_DEPT_CODE, FILE_PATH, PAGE_HTML,
    CREATE_USER_ID, CREATE_USER_NAME,
    LAST_MODIFIER_ID, LAST_MODIFIER_NAME,
    APPROVER_ID, APPROVER_NAME,
    CREATE_DATE, CONFIRM_DTIME,
    BEGINNING_DATE, EXPIRED_DATE,
    APPROVE_STATE, PAGE_TYPE, LAST_MODIFIED_DTIME,
    PAGE_DESC, PAGE_DESC_DETAIL,
    TEMPLATE_ID, THUMBNAIL, VIEW_MODE,
    USER_GUIDE, FILE_PATH_BACK, REJECTED_REASON,
    USE_YN, IS_PUBLIC, APPROVE_DATE,
    FILE_CRC_VALUE,
    FINAL_APPROVAL_STATE, FINAL_APPROVAL_DTIME,
    FINAL_APPROVAL_USER_ID, FINAL_APPROVAL_USER_NAME
  )
  SELECT
    PAGE_ID, :version,
    PAGE_NAME, OWNER_DEPT_CODE, FILE_PATH, PAGE_HTML,
    CREATE_USER_ID, CREATE_USER_NAME,
    LAST_MODIFIER_ID, LAST_MODIFIER_NAME,
    APPROVER_ID, APPROVER_NAME,
    CREATE_DATE, CONFIRM_DTIME,
    BEGINNING_DATE, EXPIRED_DATE,
    APPROVE_STATE, PAGE_TYPE, LAST_MODIFIED_DTIME,
    PAGE_DESC, PAGE_DESC_DETAIL,
    TEMPLATE_ID, THUMBNAIL, VIEW_MODE,
    USER_GUIDE, FILE_PATH_BACK, REJECTED_REASON,
    USE_YN, IS_PUBLIC, APPROVE_DATE,
    FILE_CRC_VALUE,
    FINAL_APPROVAL_STATE, FINAL_APPROVAL_DTIME,
    FINAL_APPROVAL_USER_ID, FINAL_APPROVAL_USER_NAME
  FROM SPW_CMS_PAGE
  WHERE PAGE_ID = :pageId
`;

/** 최신 버전 조회 */
export const PAGE_HISTORY_SELECT_LATEST = `
  SELECT *
  FROM SPW_CMS_PAGE_HISTORY
  WHERE PAGE_ID = :pageId
    AND VERSION = (
      SELECT MAX(VERSION)
      FROM SPW_CMS_PAGE_HISTORY
      WHERE PAGE_ID = :pageId
    )
`;

/** 특정 버전 조회 */
export const PAGE_HISTORY_SELECT_BY_VERSION = `
  SELECT *
  FROM SPW_CMS_PAGE_HISTORY
  WHERE PAGE_ID = :pageId
    AND VERSION = :version
`;

/** 이력 목록 조회 (버전 역순, 요약 정보만) — W-4: SNAPSHOT_DTIME → APPROVE_DATE */
export const PAGE_HISTORY_SELECT_LIST = `
  SELECT PAGE_ID, VERSION, PAGE_NAME, APPROVE_STATE,
         LAST_MODIFIER_ID, LAST_MODIFIER_NAME,
         APPROVE_DATE
  FROM SPW_CMS_PAGE_HISTORY
  WHERE PAGE_ID = :pageId
  ORDER BY VERSION DESC
`;

/** FILE_PATH로 HISTORY VERSION 역조회 (롤백 후 배포 fileId 결정용) — 동일 FILE_PATH가 여러 버전에 존재할 경우 최신 버전 반환 */
export const PAGE_HISTORY_SELECT_VERSION_BY_FILE_PATH = `
  SELECT VERSION
  FROM (
    SELECT VERSION
    FROM SPW_CMS_PAGE_HISTORY
    WHERE PAGE_ID   = :pageId
      AND FILE_PATH = :filePath
    ORDER BY VERSION DESC
  )
  WHERE ROWNUM = 1
`;

/** 페이지별 이력 존재 여부 (삭제 정책 판단용) */
export const PAGE_HISTORY_COUNT_BY_PAGE = `
  SELECT COUNT(*) AS CNT
  FROM SPW_CMS_PAGE_HISTORY
  WHERE PAGE_ID = :pageId
`;
