-- ============================================================================
-- V2: 페이지 조회/클릭 로그 테이블 (이슈 #186)
-- ============================================================================

-- ── 테이블 ──
CREATE TABLE SPW_CMS_PAGE_VIEW_LOG (
    LOG_ID        NUMBER         NOT NULL,
    PAGE_ID       VARCHAR2(100)  NOT NULL,
    COMPONENT_ID  VARCHAR2(100),
    EVENT_TYPE    VARCHAR2(20)   NOT NULL,
    VIEW_DTIME    TIMESTAMP(6)   DEFAULT SYSTIMESTAMP,
    CONSTRAINT PK_SPW_PAGE_VIEW_LOG  PRIMARY KEY (LOG_ID),
    CONSTRAINT FK_SPW_VIEW_LOG_PAGE  FOREIGN KEY (PAGE_ID)
        REFERENCES SPW_CMS_PAGE (PAGE_ID),
    CONSTRAINT CHK_SPW_VIEW_LOG_EVENT CHECK (EVENT_TYPE IN ('VIEW', 'CLICK'))
);

COMMENT ON TABLE  SPW_CMS_PAGE_VIEW_LOG              IS '페이지 조회/클릭 로그 [Springware CMS]';
COMMENT ON COLUMN SPW_CMS_PAGE_VIEW_LOG.LOG_ID        IS '로그 ID (시퀀스 자동 채번)';
COMMENT ON COLUMN SPW_CMS_PAGE_VIEW_LOG.PAGE_ID       IS '페이지 ID (FK → SPW_CMS_PAGE)';
COMMENT ON COLUMN SPW_CMS_PAGE_VIEW_LOG.COMPONENT_ID  IS '컴포넌트 ID (CLICK 시에만, VIEW는 NULL)';
COMMENT ON COLUMN SPW_CMS_PAGE_VIEW_LOG.EVENT_TYPE    IS '이벤트 타입 (VIEW / CLICK)';
COMMENT ON COLUMN SPW_CMS_PAGE_VIEW_LOG.VIEW_DTIME    IS '이벤트 발생 일시';

-- ── 시퀀스 + 트리거 (Oracle 11g — IDENTITY 미지원) ──
CREATE SEQUENCE SEQ_SPW_PAGE_VIEW_LOG START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_SPW_PAGE_VIEW_LOG_PK
BEFORE INSERT ON SPW_CMS_PAGE_VIEW_LOG
FOR EACH ROW
BEGIN
    SELECT SEQ_SPW_PAGE_VIEW_LOG.NEXTVAL INTO :NEW.LOG_ID FROM DUAL;
END;
/

-- ── 인덱스 ──
CREATE INDEX IDX_SPW_VIEW_LOG_PAGE_EVENT
    ON SPW_CMS_PAGE_VIEW_LOG (PAGE_ID, EVENT_TYPE);
