-- V5__request_display_period.sql
-- Separate requested display period from approved display period.

ALTER TABLE SPW_CMS_PAGE ADD (
    REQUEST_BEGINNING_DATE DATE,
    REQUEST_EXPIRED_DATE DATE
);

COMMENT ON COLUMN SPW_CMS_PAGE.REQUEST_BEGINNING_DATE IS '승인 요청 노출 시작일';
COMMENT ON COLUMN SPW_CMS_PAGE.REQUEST_EXPIRED_DATE IS '승인 요청 노출 종료일';

ALTER TABLE SPW_CMS_PAGE_HISTORY ADD (
    REQUEST_BEGINNING_DATE DATE,
    REQUEST_EXPIRED_DATE DATE
);

COMMENT ON COLUMN SPW_CMS_PAGE_HISTORY.REQUEST_BEGINNING_DATE IS '승인 요청 노출 시작일';
COMMENT ON COLUMN SPW_CMS_PAGE_HISTORY.REQUEST_EXPIRED_DATE IS '승인 요청 노출 종료일';
